### ISSUE TITLE
Generator version is nowhere to be seen

### ISSUE THREAD

**Issue by isgulkov** [seniorGolang/tg#13]
So, you generally want to know which version the code was generated with, so everyone on the team can use the same version to regenerate, producing small, meaningful diffs instead of changing each of the 30 generated files in 100 places.

Unfortunately, the generator doesn't leave any trace of its version, neither in the generated code's comments:

```go
// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
```

nor even in its own binary (that I've built from a tagged release downloaded from here):

```sh
$ tg        
NAME:
   golang service 't'ransport 'g'enerator (tg) - make Go-Kit API easy

USAGE:
   tg [global options] command [command options] [arguments...]

VERSION:
   local.dev
...
```

_Stop it! Get some help._ What command-line utility doesn't report its own version, ffs? At least put the commit hash there somewhere

**Comment by seniorGolang** [comment]
Append tg version constant in v2.2.15

**Comment by seniorGolang** [comment]
tg --version
golang service 't'ransport 'g'enerator (tg) version v2.3.21

version.go in transport package

_Stop it! Look carefully._
